{
 "title": "Hpa 메트릭",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_horizontalpodautoscaler_info, namespace)"
    }
   },
   {
    "name": "hpa",
    "query": {
     "query": "label_values(kube_horizontalpodautoscaler_info{namespace=\"$namespace\"}, horizontalpodautoscaler)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current Replicas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{\r\n  namespace=\"$namespace\",\r\n  horizontalpodautoscaler=\"$hpa\"\r\n}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Desired Replicas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_desired_replicas{\r\n  namespace=\"$namespace\",\r\n  horizontalpodautoscaler=\"$hpa\"\r\n}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scale Event Changes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "changes(\r\n  kube_horizontalpodautoscaler_status_current_replicas{\r\n    namespace=\"$namespace\",\r\n    horizontalpodautoscaler=\"$hpa\"\r\n  }[5m]\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current vs Desired",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{\r\n  namespace=\"$namespace\",\r\n  horizontalpodautoscaler=\"$hpa\"\r\n}",
     "legendFormat": "{{current}}"
    },
    {
     "expr": "kube_horizontalpodautoscaler_status_desired_replicas{\r\n  namespace=\"$namespace\",\r\n  horizontalpodautoscaler=\"$hpa\"\r\n}",
     "legendFormat": "{{Desired}}"
    }
   ]
  },
  {
   "title": "Min / Max Replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_spec_min_replicas{\r\n  namespace=\"$namespace\",\r\n  horizontalpodautoscaler=\"$hpa\"\r\n}",
     "legendFormat": "Min"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_max_replicas{\r\n  namespace=\"$namespace\",\r\n  horizontalpodautoscaler=\"$hpa\"\r\n}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Scaling Conditions ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_condition{\r\n  namespace=\"$namespace\",\r\n  horizontalpodautoscaler=\"$hpa\"\r\n}",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(\r\n  rate(container_cpu_usage_seconds_total[1m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}